import { useEffect, useState } from 'react';
import ConfirmModal from './ConfirmModal';
import Navbar from './Navbar';
import api from '../../service/api';
import '../css/styles.css';

const vacio = { id: null, viajeId: '', pagadorId: '', concepto: '', monto: '', categoria: 'OTRO', fecha: '' };

export default function AdminGastos() {
  const [gastos, setGastos] = useState([]), [viajes, setViajes] = useState([]), [usuarios, setUsuarios] = useState([]);
  const [form, setForm] = useState(null), [errores, setErrores] = useState({}), [eliminar, setEliminar] = useState(null);
  const [busqueda, setBusqueda] = useState(''), [categoria, setCategoria] = useState(''), [filtros, setFiltros] = useState({ busqueda: '', categoria: '' });
  const [pagina, setPagina] = useState(0), [totalPaginas, setTotalPaginas] = useState(1), [solicitud, setSolicitud] = useState(0);
  const [loading, setLoading] = useState(true), [error, setError] = useState('');

  useEffect(() => { let activo = true; Promise.all([api.get('/viajes', { params: { page: 0, size: 50 } }), api.get('/usuarios/paginados', { params: { page: 0, size: 50, activo: true } })]).then(([v, u]) => { if (activo) { setViajes(v.data?.contenido ?? []); setUsuarios(u.data?.contenido ?? []); } }); return () => { activo = false; }; }, []);
  useEffect(() => { let activo = true; api.get('/gastos/paginados', { params: { page: pagina, size: 10, busqueda: filtros.busqueda || undefined, categoria: filtros.categoria || undefined } }).then(({ data }) => { if (activo) { setGastos(data?.contenido ?? []); setTotalPaginas(Math.max(data?.totalPaginas ?? 1, 1)); } }).catch(() => { if (activo) setError('No fue posible cargar los gastos.'); }).finally(() => { if (activo) setLoading(false); }); return () => { activo = false; }; }, [filtros, pagina, solicitud]);
  const abrir = (gasto = vacio) => setForm({ ...vacio, ...gasto, viajeId: gasto.viajeId || viajes[0]?.id || '', pagadorId: gasto.pagadorId || usuarios[0]?.id || '', fecha: gasto.fecha || new Date().toISOString().slice(0, 10) });
  const guardar = async (e) => { e.preventDefault(); const nuevos = {}; if (!form.viajeId) nuevos.viajeId = 'Selecciona un viaje.'; if (!form.pagadorId) nuevos.pagadorId = 'Selecciona un pagador.'; if (!form.concepto.trim()) nuevos.concepto = 'El concepto es obligatorio.'; if (!(Number(form.monto) > 0)) nuevos.monto = 'El monto debe ser mayor a 0.'; if (!form.fecha) nuevos.fecha = 'La fecha es obligatoria.'; setErrores(nuevos); if (Object.keys(nuevos).length) return; try { const payload = { ...form, viajeId: Number(form.viajeId), pagadorId: Number(form.pagadorId), monto: Number(form.monto) }; if (form.id) await api.put(`/gastos/${form.id}`, payload); else await api.post('/gastos', payload); setForm(null); setLoading(true); setSolicitud((v) => v + 1); } catch (err) { setError(err.response?.data?.mensaje || 'No fue posible guardar el gasto.'); } };
  const confirmarEliminar = async () => { try { await api.delete(`/gastos/${eliminar.id}`); setEliminar(null); setLoading(true); setSolicitud((v) => v + 1); } catch { setError('No fue posible eliminar el gasto.'); } };
  const buscar = () => { setLoading(true); setPagina(0); setFiltros({ busqueda: busqueda.trim(), categoria }); setSolicitud((v) => v + 1); };
  const cambiarPagina = (valor) => { setLoading(true); setPagina(valor); };
  const categorias = ['TRANSPORTE', 'HOSPEDAJE', 'COMIDA', 'ENTRETENIMIENTO', 'OTRO'];

  return <><Navbar /><main className="page"><div className="container"><div className="page-head"><div><span className="eyebrow">CRUD DE GASTOS</span><h1>Gastos</h1><p className="muted">Administra los gastos de todos los viajes.</p></div><button className="button primary" onClick={() => abrir()}>＋ Nuevo gasto</button></div><section className="filters admin-trip-filters"><input value={busqueda} onChange={(e) => setBusqueda(e.target.value)} placeholder="Concepto, viaje o pagador" /><select value={categoria} onChange={(e) => setCategoria(e.target.value)}><option value="">Todas las categorías</option>{categorias.map((c) => <option key={c}>{c}</option>)}</select><button className="button ghost" onClick={buscar}>Buscar</button></section>{error && <p className="banner warn">{error}</p>}{loading ? <div className="card panel admin-loading"><div className="spinner"></div></div> : <div className="table-wrap"><table><thead><tr><th>Concepto</th><th>Viaje</th><th>Pagador</th><th>Fecha</th><th>Monto</th><th>Acciones</th></tr></thead><tbody>{gastos.map((g) => <tr key={g.id}><td><strong>{g.concepto}</strong><br /><span className="muted">{g.categoria}</span></td><td>{g.viajeNombre}</td><td>{g.pagadorNombre}</td><td>{new Date(`${g.fecha}T00:00:00`).toLocaleDateString('es-MX')}</td><td>${Number(g.monto).toLocaleString('es-MX')}</td><td><div className="admin-actions"><button className="button ghost small" onClick={() => abrir(g)}>Editar</button><button className="button danger small" onClick={() => setEliminar(g)}>Eliminar</button></div></td></tr>)}{!gastos.length && <tr><td colSpan="6" className="admin-empty">No se encontraron gastos.</td></tr>}</tbody></table></div>}{!loading && totalPaginas > 1 && <div className="pagination"><button disabled={!pagina} onClick={() => cambiarPagina(pagina - 1)}>‹</button><span className="admin-page-count">Página {pagina + 1} de {totalPaginas}</span><button disabled={pagina + 1 >= totalPaginas} onClick={() => cambiarPagina(pagina + 1)}>›</button></div>}</div></main>
  <div className={`modal-backdrop ${form ? 'open' : ''}`}><div className="modal admin-form-modal"><h3>{form?.id ? 'Editar gasto' : 'Nuevo gasto'}</h3>{form && <form onSubmit={guardar}><label className="field"><span>Viaje *</span><select value={form.viajeId} onChange={(e) => setForm({ ...form, viajeId: e.target.value })}>{viajes.map((v) => <option key={v.id} value={v.id}>{v.nombre}</option>)}</select>{errores.viajeId && <small className="error-text">{errores.viajeId}</small>}</label><label className="field"><span>Pagador *</span><select value={form.pagadorId} onChange={(e) => setForm({ ...form, pagadorId: e.target.value })}>{usuarios.map((u) => <option key={u.id} value={u.id}>{u.nombre}</option>)}</select>{errores.pagadorId && <small className="error-text">{errores.pagadorId}</small>}</label><label className="field"><span>Concepto *</span><input value={form.concepto} onChange={(e) => setForm({ ...form, concepto: e.target.value })} />{errores.concepto && <small className="error-text">{errores.concepto}</small>}</label><div className="form-grid"><label className="field"><span>Monto *</span><input type="number" min="0.01" step="0.01" value={form.monto} onChange={(e) => setForm({ ...form, monto: e.target.value })} />{errores.monto && <small className="error-text">{errores.monto}</small>}</label><label className="field"><span>Fecha *</span><input type="date" value={form.fecha} onChange={(e) => setForm({ ...form, fecha: e.target.value })} />{errores.fecha && <small className="error-text">{errores.fecha}</small>}</label></div><label className="field"><span>Categoría</span><select value={form.categoria} onChange={(e) => setForm({ ...form, categoria: e.target.value })}>{categorias.map((c) => <option key={c}>{c}</option>)}</select></label><div className="modal-actions"><button type="button" className="button ghost" onClick={() => setForm(null)}>Cancelar</button><button className="button primary">Guardar</button></div></form>}</div></div><ConfirmModal isOpen={Boolean(eliminar)} title="Eliminar gasto" message="Esta acción no se puede deshacer." confirmText="Eliminar" onConfirm={confirmarEliminar} onCancel={() => setEliminar(null)} /></>;
}
