name: local
variables:
  - name: baseUrl
    value: http://localhost:8080
    description: ""
  - name: usuarioId
    value: "5"
    description: ""
  - name: viajeId
    value: "2"
    description: ""
  - name: participanteId
    value: "1"
    description: ""
  - name: actividadId
    value: "1"
    description: ""
  - name: gastoId
    value: "1"
    description: ""
  - name: rolId
    value: "1"
    description: ""
  - name: token
    value: ""
    description: ""
  - name: usuarioCorreo
    value: admin@gmail.com
    description: ""
  - name: organizadorId
    value: "2"
    description: ""
  - name: pagadorId
    value: "2"
    description: ""
  - name: adminToken
    value: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbkBydXRlYXBwLmNvbSIsInVzdWFyaW9JZCI6MSwibm9tYnJlIjoiQWRtaW5pc3RyYWRvciBQcnVlYmEiLCJyb2wiOiJBRE1JTklTVFJBRE9SIiwiaWF0IjoxNzg1MTIxMjczLCJleHAiOjE3ODUyMDc2NzN9.FnR4j3xePpq3CudOfVzEbxMiVQF0Y7r5rMGQ47LJ2LWIxM7DTctdqyz6TdpAbaYa
    description: ""
  - name: usuarioToken
    value: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c3VhcmlvQHJ1dGVhcHAuY29tIiwidXN1YXJpb0lkIjoyLCJub21icmUiOiJVc3VhcmlvIEFjdHVhbGl6YWRvIiwicm9sIjoiVVNVQVJJTyIsImlhdCI6MTc4NTEyMTU2NywiZXhwIjoxNzg1MjA3OTY3fQ.rusEoj_jM_NlHm9XWQfIp2oXc9Re6u1mejs6lW_RDhd3cifmZNsNdIkS6gFfGDD9
    description: ""
  - name: agenciaToken
    value: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZ2VuY2lhQHJ1dGVhcHAuY29tIiwidXN1YXJpb0lkIjozLCJub21icmUiOiJBZ2VuY2lhIFBydWViYSIsInJvbCI6IkFHRU5DSUEiLCJpYXQiOjE3ODUwODQwNjgsImV4cCI6MTc4NTE3MDQ2OH0.DCuI2i2I46ZGMNSGsS7SM6FMXGtQDshDpB_49De43MsFBvCAkv2dURfmmmUBdEBl
    description: ""
