spring.application.name=ruteapp

spring.datasource.url=jdbc:mysql://localhost:3306/ruteapp_db
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_CONTRASENA

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=CLAVE_SECRETA
jwt.expiration=86400000