info:
  name: CREAR ROL ORGANIZADOR
  type: http
  seq: 1

http:
  method: POST
  url: "{{baseUrl}}/api/roles"
  body:
    type: json
    data: |-
      {
        "nombre": "ORGANIZADOR"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
