info:
  name: CREAR ROL ADMINISTRADOR
  type: http
  seq: 2

http:
  method: POST
  url: "{{baseUrl}}/api/roles"
  body:
    type: json
    data: |-
      {
        "nombre": "ADMINISTRADOR"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
